version: "3"
services:

  datastore:
    image: golosblockchain/web-ui:datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    volumes:
      - ./tarantool:/var/lib/tarantool
    ports:
      - "3301:3301"

  datafeed:
    image: golosblockchain/web-ui:datafeed
    build:
      context: .
      dockerfile: Dockerfile-datafeed
    restart: unless-stopped
    depends_on:
      - datastore
    environment:
      NODE_URL: https://api.golos.id
      TARANTOOL_HOST: datastore

  dataserver:
    image: golosblockchain/web-ui:dataserver
    build:
      context: .
      dockerfile: Dockerfile-dataserver
    restart: unless-stopped
    depends_on:
      - datastore
    environment:
      NODE_URL: https://api.golos.id
      TARANTOOL_HOST: datastore
    ports:
      - "8805:8805"
