version: "3"
services:

  datastore:
    image: golosblockchain/web-ui:datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    volumes:
      - ./tarantool:/var/lib/tarantool
    ports:
      - "3001:3001"

  datafeed:
    image: golosblockchain/web-ui:datafeed
    build:
      context: .
      dockerfile: Dockerfile-datafeed
    restart: unless-stopped
    depends_on:
      - datastore
    environment:
      NODE_URL: https://api.golos.id
      TARANTOOL_HOST: datastore